### ISSUE TITLE
Travis build script attempts deployment for pull request against fork

### ISSUE THREAD

**Issue by arstrube** [basvodde/travis_github_deployer#7]
I created a pull request against my fork, arstrube/cpputest. As I understand it, the deployer should recognize pull requests and not attempt deployment.

However, it does attempt deployment and this causes the build to fail.

The full log of the build is here:

https://raw.githubusercontent.com/arstrube/images/master/travis_github_deployer/log.txt

The fault seems to be within the travis_github_deployer itself.

**Comment by arstrube** [comment]
P.S. It would be even nicer if the travis_github_deployer recognized it's being run on a fork and didn't do deployment in the first place, pull request or no. But fixing this issue for pull requests would be okay for now.

**Comment by arstrube** [comment]
Hi Bas,
Could we maybe get this one fixed? Maybe that would make it easier to deal with https://github.com/cpputest/cpputest/issues/379.

**Comment by basvodde** [comment]
I won't be able to fix it right now, I'll see if I have an evening for this this week. Bit busy times...

**Comment by arstrube** [comment]
``` ruby
    ENV['TRAVIS_PULL_REQUEST']="10"
```

Why "10"? According to github documentation, it contains the number of the pull request, which is definitiely not "10", unless of course it happens to be pull request #10. The strange thing is that this does seem to work on cpputest/cpputest.

How avout trying:

``` ruby
ENV['TRAVIS_PULL_REQUEST']!="false"
```

Would that work, perhaps?

Then again, the variable might not be set when I do a pull request against my own fork. Another way would be to test whether GIT_NAME is set (which it won't be; that's why the deployment attempt failed).

**Comment by arstrube** [comment]
Yeah, I figured you are quite busy right now.... As you can see I am peeking and poking here and there but not being familiar with either Ruby or Travis internals that's a bit of guesswork...

**Comment by arstrube** [comment]
Something to the tune of:

``` ruby
it "will not deploy on a pull request" do
    ENV['TRAVIS_PULL_REQUEST']="10" OR ENV['GIT_NAME ']="false"
    subject.should_not_receive(:load_configuration)
    subject.should_receive(:puts).with("In pull request and won't be deploying")
    subject.deploy
end
```

**Comment by basvodde** [comment]
Yah, soon you'll switch to Ruby... be careful :P

**Comment by arstrube** [comment]
I wasn't. But I gave up all the same. The problem was, I had to get Travis to build with my modified gem for testing. This went totally uncontrollable. I pushed travis_github_deployer2-0.2.5test to rubygem.org and that was a BIG mistake. For some reason, it is not possible to do

``` bash
gem install travis_github_deployer2
```

yet the bloody thing gets downloads by the dozens and it wasn't supposed to be for others, and on top of it it's apparently undeletable. What a mess!

**Comment by arstrube** [comment]
In any case, herewith demote the issue from "Bug" to "Feature Request", because...
- ...Pull requests don't attempt to deploy. So no bug.
- ...Normal builds do attempt to deploy. The code I suggested above would fix that.
  The nice thing is that contributors could then have Travis run against their own commits and they wouldn't be condemned to failing anymore. Sorry I couldn't do proper tests, and for the mess I made in attempting to do some testing :P. My apologies.

**Comment by arstrube** [comment]
It should probably output the appropriate message. So we'd better add a new "paragraph" like

``` ruby
it "will not deploy on a fork" do
    ENV['GIT_NAME ']="false"
    subject.should_not_receive(:load_configuration)
    subject.should_receive(:puts).with("In fork and won't be deploying")
    subject.deploy
end
```

 Not quite sure why subject.deploy is in there ?

**Comment by basvodde** [comment]
The subject.deploy is the action from the test code to the production code :) Without it, there wouldn't be any production code run.

**Comment by arstrube** [comment]
So the above would be a suitable test for the functionality I would like to see, right?

**Comment by arstrube** [comment]
Sorry I feel really really stupid now.... :-(

**Comment by arstrube** [comment]
Well okay. Test first. Leaves only two questions: Where does the code go, and how do I run the tests (presuming I got xxx.gemfile and Ruby installed)......

**Comment by basvodde** [comment]
Eh, don't worry about it. The above looks like a good test, but the question is (I put in another thread), when would this happen?

**Comment by basvodde** [comment]
You can run the specs (ruby tests) with rake spec

**Comment by arstrube** [comment]
This happens when running the travis build script on a fork. GIT_NAME isn't defined then for security reasons. This is what makes builds on forks fail. It should never happen on cpputest/cpputest (see the log I linked above). So if I catch the condition the same way as the pull request condition, then github deployer wont fail on the undefined GIT_NAME but bail out gracefully, allowing us ordinariy people to get decent Travis runs on our commits :-).

**Comment by arstrube** [comment]
Oh. So specs == tests. Go figure ;-). Will try running it tonight...

**Comment by arstrube** [comment]
I got very close to running a life test -- however, the gemfile I built and passed to Travis seemed faulty -- had some unresolved dependencies. Anyhow, if I get the above test to pass I'll update the pull request. Thank you for your patience -- much appreciated!

**Comment by arstrube** [comment]
rake spec doesn't like:

``` ruby
@git = mock
```

I have rspec-mocks installed. Why?

**Comment by arstrube** [comment]
Phew. There was more to this than meets the naked eye.

(N.B. the above line of code is beyond deprecation -- it has been made illegal).

**Comment by arstrube** [comment]
Was very hard to find, because people keep talking Mock, but there is never any code with "mock" in it. I think this change is a bit unfortunate.

**Comment by arstrube** [comment]
spec -> specification by example. kewl, actually.

**Comment by arstrube** [comment]
I guess version 0.2.4 still needs to be pushed up to RubyGem.org or something like that?

**Comment by arstrube** [comment]
P.S. How exactly do you build your gem? I built mine and threw it at Travis, but Travis barked:

```
/home/travis/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/
kernel_require.rb:121:in `require': cannot load such file
```

**Comment by basvodde** [comment]
You can build a gem with "gem build" :P

I think you can't push a new version of the gem though. I just pushed it up, should be there now.

**Comment by arstrube** [comment]
Yup it's there. -- I know I can't push it up; I tweaked travis.yml to use a local copy for install. The install went okay. But then maybe my "gem build" is different to your "gem build" ??? So the above error came at deployment time.

Travis is running on my for now.... It picked up the new version, so let's see whether everything works as expected :-)

**Comment by arstrube** [comment]
Yihaaa. The first green build on my fork, ever:

https://travis-ci.org/arstrube/cpputest/builds/34085556

All working as expected.
